# Created by: Nicola Vitale	<nivit@FreeBSD.org>
# $FreeBSD: head/graphics/py-gchartwrapper/Makefile 370023 2014-10-04 23:59:47Z wg $

PORTNAME=	GChartWrapper
PORTVERSION=	0.9
PORTREVISION=	3
CATEGORIES=	graphics python
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python Google Chart Wrapper

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}pillow>0:${PORTSDIR}/graphics/py-pillow

PROJECTHOST=	google-chartwrapper

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
