# Created by: Choe, Cheng-Dae
# $FreeBSD: head/devel/py-configobj/Makefile 377790 2015-01-24 13:25:14Z nivit $

PORTNAME=	configobj
PORTVERSION=	5.0.6
PORTREVISION=	0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple but powerful config file reader and writer

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
