# Created by: Choe, Cheng-Dae
# $FreeBSD: head/devel/py-configobj/Makefile 372347 2014-11-09 09:07:04Z marino $

PORTNAME=	configobj
PORTVERSION=	4.7.2
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	http://www.voidspace.org.uk/downloads/ \
		SF \
		${MASTER_SITE_GOOGLE_CODE}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple but powerful config file reader and writer

LICENSE=	BSD3CLAUSE

USES=		python zip
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
