# Created by: Choe, Cheng-Dae
# $FreeBSD: head/devel/py-configobj/Makefile 347405 2014-03-07 16:49:09Z bapt $

PORTNAME=	configobj
PORTVERSION=	4.7.2
CATEGORIES=	devel python
MASTER_SITES=	http://www.voidspace.org.uk/downloads/ \
		SF \
		${MASTER_SITE_GOOGLE_CODE}

PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple but powerful config file reader and writer

USES=		zip
USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
