# Created by: Dryice Liu	<dryice@dryice.name>
# $FreeBSD: head/www/py-paste/Makefile 376109 2015-01-03 08:41:20Z mva $

PORTNAME=	Paste
PORTVERSION=	1.7.5.1
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Tools for using a Web Server Gateway Interface stack

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
