# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/net/py-speedtest-cli/Makefile 350563 2014-04-08 03:09:01Z nivit $

PORTNAME=	speedtest-cli
PORTVERSION=	0.2.5
#PORTREVISION=	0
CATEGORIES=	net
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Command line interface for testing internet bandwidth

LICENSE=	APACHE20

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
