# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/net/py-speedtest-cli/Makefile 371449 2014-10-24 16:21:26Z mva $

PORTNAME=	speedtest-cli
PORTVERSION=	0.2.5
#PORTREVISION=	0
CATEGORIES=	net
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Command line interface for testing internet bandwidth

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
