# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/www/py-pafy/Makefile 361731 2014-07-14 03:19:43Z nivit $

PORTNAME=	pafy
PORTVERSION=	0.3.54
#PORTREVISION=	0
CATEGORIES=	www
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pafy-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python API for YouTube

LICENSE=	GPLv3

# This port installs the following files in shared dirs
# PLIST_FILES=	bin/ytdl
PYDISTUTILS_AUTOPLIST=	yes

USE_PYDISTUTILS=	yes
USE_PYTHON=	yes

.include <bsd.port.mk>
