# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/www/py-pafy/Makefile 379020 2015-02-14 21:20:30Z nivit $

PORTNAME=	pafy
PORTVERSION=	0.3.72
#PORTREVISION=	0
CATEGORIES=	www
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTFILES=	Pafy-${PORTVERSION}.tar.gz

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python API for YouTube

LICENSE=	GPLv3

USES=	python
USE_PYTHON=	autoplist distutils

WRKSRC=	${WRKDIR}/${DISTFILES:R:R}

.include <bsd.port.mk>
