# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/textproc/py-pygments/Makefile 361999 2014-07-15 20:00:43Z adamw $

PORTNAME=	pygments
PORTVERSION=	1.6
PORTREVISION=	2
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pygments-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Syntax highlighter written in Python

LICENSE=	BSD2CLAUSE

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
