# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-Breve/Makefile 357277 2014-06-10 07:39:01Z olgeni $

PORTNAME=	Breve
PORTVERSION=	1.3.0
PORTREVISION=	2
CATEGORIES=	devel python
MASTER_SITES=	http://breve.twisty-industries.com/downloads/ \
		LOCAL/nivit/${PORTNAME}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python s-expression style template engine

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=yes

.include <bsd.port.mk>
