# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD$

PORTNAME=	shutter
PORTVERSION=	0.93.1
#PORTREVISION=	0
CATEGORIES=
MASTER_SITES=	http://shutter-project.org/wp-content/uploads/releases/tars/

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Screenshot tool

.include <bsd.port.mk>
