# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD$

PORTNAME=	shutter
PORTVERSION=	0.93.1
#PORTREVISION=	0
CATEGORIES=	deskutils
MASTER_SITES=	http://shutter-project.org/wp-content/uploads/releases/tars/

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Screenshot tool

LICENSE=	GPLv3 GPLv2 # the latter for some shipped cursors
LICENSE_COMB=	multi

.include <bsd.port.mk>
