# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/security/py-ed25519ll/Makefile 357852 2014-06-15 09:14:01Z mva $

PORTNAME=	ed25519ll
PORTVERSION=	0.6
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Low-level ctypes wrapper for Ed25519 digital signatures

LICENSE=	MIT

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
