# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/www/py-bottle/Makefile 349691 2014-03-30 22:18:35Z nivit $

PORTNAME=	bottle
PORTVERSION=	0.12.7
PORTREVISION=	0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Fast and simple WSGI-framework for small web-applications

LICENSE=	MIT

USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
