# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-clint/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	clint
PORTVERSION=	0.3.7
#PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python command-line application tools

LICENSE=	ISCL

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}args>=0.1.0:${PORTSDIR}/devel/py-args

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
