# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-clint/Makefile 362171 2014-07-18 01:55:41Z nivit $

PORTNAME=	clint
PORTVERSION=	0.3.7
#PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python command-line application tools

LICENSE=	ISCL

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}args>=0.1.0:${PORTSDIR}/devel/py-args

PYDISTUTILS_AUTOPLIST=	yes

USE_PYDISTUTILS=	yes
USE_PYTHON=	yes

.include <bsd.port.mk>
