# $FreeBSD: head/devel/py-argh/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	argh
PORTVERSION=	0.25.0
PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple (Python) argparse wrapper

LICENSE=	LGPL3

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
