# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/archivers/quazip/Makefile 348485 2014-03-17 15:54:22Z swills $

PORTNAME=	quazip
PORTVERSION=	0.6.2
CATEGORIES=	archivers
MASTER_SITES=	SF

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Qt/C++ wrapper for ZIP/UNZIP package

LICENSE=	LGPL21

USES=		qmake
USE_LDCONFIG=	yes
USE_QT4=	corelib moc_build qtestlib

.include <bsd.port.mk>
