# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-args/Makefile 362170 2014-07-18 01:53:41Z nivit $

PORTNAME=	args
PORTVERSION=	0.1.0
#PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Command arguments for humans

LICENSE=	BSD2CLAUSE

PYDISTUTILS_AUTOPLIST=	yes

USE_PYDISTUTILS=	yes
USE_PYTHON=	yes

.include <bsd.port.mk>
