# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD$

PORTNAME=	variety
PORTVERSION=	0.5.3
#PORTREVISION=	0
CATEGORIES=	graphics
MASTER_SITES=	https://launchpad.net/variety/trunk/${PORTVERSION}/+download/ 
		http://nivit.altervista.org/FreeBSD/ports/distfiles/
DISTNAME=	variety_${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Wallpaper changer

.include <bsd.port.mk>
