# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD$

PORTNAME=	variety
PORTVERSION=	0.5.3
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	graphics
MASTER_SITES=	https://launchpad.net/variety/trunk/${PORTVERSION}/+download/
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
DISTNAME=	variety_${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
