# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/devel/py-xerox/Makefile 362172 2014-07-18 01:56:36Z nivit $

PORTNAME=	xerox
PORTVERSION=	0.3.1
#PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Simple copy and paste in Python

LICENSE=	MIT

PYDISTUTILS_AUTOPLIST=	yes

USE_PYDISTUTILS=	yes
USE_PYTHON=	yes

.include <bsd.port.mk>
