# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/audio/py-mpd/Makefile 343448 2014-02-09 10:31:37Z miwi $

PORTNAME=	mpd
PORTVERSION=	0.3.0
PORTREVISION=	1
#PORTEPOCH=	0
CATEGORIES=	audio python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	python-${PORTNAME}-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Python MPD client library

USE_PYTHON=	yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes


.include <bsd.port.mk>
