# Created by: ijliao
# $FreeBSD: head/graphics/py-chart/Makefile 353381 2014-05-09 03:05:05Z vanilla $

PORTNAME=	chart
PORTVERSION=	1.39
PORTREVISION=	5
CATEGORIES=	graphics python
MASTER_SITES=	http://download.gna.org/pychart/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	PyChart-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Create high quality Encapsulated Postscript, PDF, or PNG charts

LICENSE=	GPLv2

USE_GHOSTSCRIPT_RUN=	yes
USE_PYTHON=	distutils,autoplist
USES=		python:2.7

.include <bsd.port.mk>
