# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/net-im/py-skype4py/Makefile 358741 2014-06-21 20:33:23Z mva $

PORTNAME=	Skype4Py
PORTVERSION=	1.0.35
PORTREVISION=	1
CATEGORIES=	net-im devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Skype (TM) API wrapper for Python

LICENSE=	BSD3CLAUSE

USE_PYTHON=		2
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes
USES=		zip

.include <bsd.port.mk>
